client: battleship_client.cc
	g++ -g -o battleship_client battleship_client.cc -lboost_system -lboost_thread -lpthread -lncurses
server: battleship_server.cc
	g++ -g -o battleship_server battleship_server.cc -lboost_system -lboost_thread -lpthread -lncurses
server_run:server
	./battleship_server
